sonata_admin:
    security:
      handler: sonata.admin.security.handler.role
      role_admin: ROLE_ADMIN

    title: 'API Admin'
    
    search : false

    options:
      list_action_button_content: icon
                    
    templates:
        user_block: 'Admin/Sonata/Core/user_block.html.twig'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

